force-app/main/default/objects/MJS_StubData__mdt/MJS_StubData__mdt.object-meta.xml
<CustomObject>
    <description>Use this class to return configurable data using Salesforce&apos;s StubProvider interface.</description>
    <label>Stub Data</label>
    <pluralLabel>Stub Data</pluralLabel>
</CustomObject>

force-app/main/default/objects/MJS_StubData__mdt/fields/MJS_ListOfArgs__c.field-meta.xml
<CustomField>
    <fullName>MJS_ListOfArgs__c</fullName>
    <description>Matches the listOfArgs parameter of the handleMethodCall method.</description>
    <label>List Of Args</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJS_StubData__mdt/fields/MJS_ListOfParamNames__c.field-meta.xml
<CustomField>
    <fullName>MJS_ListOfParamNames__c</fullName>
    <description>Matches the listOfParamNames parameter of the handleMethodCall method.</description>
    <label>List Of Param Names</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJS_StubData__mdt/fields/MJS_ListOfParamTypes__c.field-meta.xml
<CustomField>
    <fullName>MJS_ListOfParamTypes__c</fullName>
    <description>Matches the listOfParamTypes parameter of the handleMethodCall method.</description>
    <label>List Of Param Types</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJS_StubData__mdt/fields/MJS_ReturnType__c.field-meta.xml
<CustomField>
    <fullName>MJS_ReturnType__c</fullName>
    <description>Matches the returnType parameter of the handleMethodCall method.</description>
    <label>Return Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJS_StubData__mdt/fields/MJS_StubbedMethodName__c.field-meta.xml
<CustomField>
    <fullName>MJS_StubbedMethodName__c</fullName>
    <description>Matches the stubbedMethodName parameter of the handleMethodCall method.</description>
    <label>Stubbed Method Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJS_StubData__mdt/fields/MJS_StubbedObject__c.field-meta.xml
<CustomField>
    <fullName>MJS_StubbedObject__c</fullName>
    <description>Matches the stubbedObject parameter of the handleMethodCall method.</description>
    <label>Stubbed Object</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MJS_StubData__mdt/fields/MJS_Value__c.field-meta.xml
<CustomField>
    <fullName>MJS_Value__c</fullName>
    <description>The returned data is in JSON format.</description>
    <label>Value</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MJS_StubDataProvider.cls
@IsTest
public without sharing class MJS_StubDataProvider implements System.StubProvider
{
	private final static String CLASS_NAME_MARKER = '__sfdc_';

	/**
	 * @description This method is called by the Test.createStub() API to handle method calls on the stubbed object.
	 * 				It retrieves the stub data from the custom metadata type MJS_StubData__mdt based on the parameters
	 * 				provided and returns the corresponding value that is then deserialized to the expected return type.
	 */
	public Object handleMethodCall(Object stubbedObject, String stubbedMethodName, Type returnType, List<Type> listOfParamTypes, List<String> listOfParamNames, List<Object> listOfArgs) 
	{
		// Convert everything to string for easier comparison
		string className = stubbedObject.toString().left(stubbedObject.toString().indexOf(CLASS_NAME_MARKER));
		string returnTypeName = returnType.toString();
		string listOfParamTypeValues = listOfParamTypes.toString();
		string listOfParamNameValues = JSON.serialize(listOfParamNames);
		string listOfArgValues = JSON.serialize(listOfArgs);

		// System.debug('---');
		// System.debug('Stubbed Object: ' 		+ className);
		// System.debug('Stubbed Method Name: ' + stubbedMethodName);
		// System.debug('Return Type: ' 		+ returnTypeName);
		// System.debug('List of Param Types: ' + listOfParamTypeValues);
		// System.debug('List of Param Names: ' + listOfParamNameValues);
		// System.debug('List of Args: ' 		+ listOfArgValues);
		// System.debug('---');

		/**
		 * IMPORTANT
		 * The framework assumes that entries in the MJS_StubData__mdt custom metadata type are unique based on the combination of the following fields:
		 *   - MJS_StubbedObject__c
		 *   - MJS_StubbedMethodName__c
		 *   - MJS_ReturnType__c
		 *   - MJS_ListOfParamTypes__c
		 *   - MJS_ListOfParamNames__c
		 *   - MJS_ListOfArgs__c
		 */
		if(	String.isNotBlank(className) && 
			String.isNotBlank(stubbedMethodName) && 
			String.isNotBlank(returnTypeName) && 
			String.isNotBlank(listOfParamTypeValues) && 
			String.isNotBlank(listOfParamNameValues) && 
			String.isNotBlank(listOfArgValues))
		{
			List<MJS_StubData__mdt> results = [	SELECT	MJS_Value__c 
												FROM	MJS_StubData__mdt 
												WHERE	MJS_StubbedObject__c = :className AND 
														MJS_StubbedMethodName__c = :stubbedMethodName AND 
														MJS_ReturnType__c = :returnTypeName AND 
														MJS_ListOfParamTypes__c = :listOfParamTypeValues AND 
														MJS_ListOfParamNames__c = :listOfParamNameValues AND 
														MJS_ListOfArgs__c = :listOfArgValues];
			if(results.size() > 0)
			{
				return JSON.deserialize(results[0].MJS_Value__c, returnType);
			}
		}

		return null;
	}
}